### ISSUE TITLE
wrong bundle paths with browserHistory

### ISSUE THREAD

**Issue by Eschon** [luqin/react-router-loader#15]
When I included react-router-loader into my project I was using hashHistory with react-router. I tried switching to browserHistory I noticed that bundle urls are wrong when directly accessing a route.

I have my routes set up like this:

```
<Router history={browserHistory}
    <Route path="/" component={App}>
        <IndexRoute component={GridWrapper} />
        <Route path="/resorts" component={require('react-router!./modules/Resorts')} />
        <Route path="/resorts/:resort" component={require('react-router!./modules/Resort')} />
        <Route path="/community/tracks" component={require('react-router!./modules/Tracks')} />
    </Route>
</Router>
```

The output of my webpack configuration is:

```
output: {
    path: './dist/js',
    filename: 'bundle.js',
    publicPath: '/js/'
}
```

And I start my webpack-dev-server like this:
`webpack-dev-server --content-base dist/ --history-api-fallback --inline --hot --host 0.0.0.0`

Now when I navigate my browser to navigate to `http://localhost:8080/resorts/7353` I get the following error in the browser console: `GET http://localhost:8080/resorts/js/bundle.js 404 (Not Found)`. However if I just open `http://localhost:8080/` and navigate there with react-router links it works.

Is this a bug or is there something wrong with my configuration?

**Comment by luqin** [comment]
Hi. You can have a try with: https://github.com/reactjs/react-router/blob/master/docs/guides/DynamicRouting.md

**Comment by Eschon** [comment]
I'm not sure how to interpret your answer. Are you suggesting that I should try that instead of react-router-loader?

**Comment by Eschon** [comment]
Ok sorry this has nothing todo with react-router-loader, it was an error on my side. I just noticed that i used a relative path for the bundle.js in my html file. Using an absolute path fixed the prolbem.

**Comment by luqin** [comment]
:+1:
