### ISSUE TITLE
react-router-loader设置Named chunks的问题

### ISSUE THREAD

**Issue by baizn** [luqin/react-router-loader#3]
设置Named chunks后每次加载的都基本有3M的js，

路由配置如上，应该怎么处理让每次只加载几十或几百KB呢 ？

**Comment by luqin** [comment]
能贴个具体的react-router配置和webpack配置吗

**Comment by baizn** [comment]
webpack:
![image](https://cloud.githubusercontent.com/assets/9443867/11364034/80209f68-92d8-11e5-8532-ee030f9c7ef9.png)
router:
![image](https://cloud.githubusercontent.com/assets/9443867/11364039/911fd860-92d8-11e5-9e6c-e39dd63eac8c.png)
这个模块划分应该按怎样的原则分呢 ？  另外需要其他什么配置不 ？

**Comment by luqin** [comment]
我一般是每个文件对应一个React组件（React开发风格也推荐这样做），然后这样使用：

``` js
<Route component={require('react-router!./User')} />
```

**Comment by luqin** [comment]
@baizn echarts 可以使用 npm 里的包安装。示例：https://github.com/luqin/echarts-webpack-starter-kit
