### ISSUE TITLE
Named chunks，文件名替换不生效

### ISSUE THREAD

**Issue by Liyuk** [luqin/react-router-loader#6]
``` javascript
1. <Route component={require('react-router!./Component')} />
2. <Route component={require('react-router?name=chunkName!./Component')} />
```
- 第一条语句执行时，按模块拆分了js，文件名是数字，例如`0.js`、`1.js`；
- 第二条语句执行时，没有分模块打包js，全部打成了一个名为`chunkName.js`的文件。

想问下第二种语句不执行是我哪里配置有问题，还是少配置了什么文件？
我检查了下`node_modules`里面有`loader-utils`。

O(∩_∩)O谢谢

**Comment by Liyuk** [comment]
_(:з」∠)_找到答案了，求关闭折叠。。

**Comment by Liyuk** [comment]
#3

**Comment by luqin** [comment]
webpack 的 chunkname 也需要包含 [name]
