### ISSUE TITLE
使用 browserHistory 的时候带参数路由问题

### ISSUE THREAD

**Issue by qieqing** [luqin/react-router-loader#7]
在使用 browserHistory 的时候匹配以下路由，JS加载路径有问题，使用 hashHistory 则正常
`<Route path="/messages/:id" component={require('react-router!./Message')}>`

页面URL是类似：http://127.0.0.1:8080/messages/32432

![image](https://cloud.githubusercontent.com/assets/69210/12810295/4d7032f2-cb60-11e5-9de3-f21643c5618e.png)

**Comment by qieqing** [comment]
@luqin 已经解决了，是Webpack配置问题，Thks

**Comment by hhb0508** [comment]
想问下是怎么解决的
